version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reservation-backend
    ports:
      - "5000:5000"      # Port exposé sur la machine
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - reservation-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reservation-frontend
    ports:
      - "8084:80"        # Port exposé sur la machine
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000  # <-- Permet au frontend de communiquer avec le backend via Docker
    restart: unless-stopped
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge
